import { headers } from "next/headers"
import { redirect } from "next/navigation"
import { auth } from "@/lib/auth"
import { getProfile, getWishlist } from "@/lib/railway"

export default async function AdminPanel() {
  const session = await auth.api.getSession({ headers: await headers() }); if (!session?.user) redirect("/admin")
  let profile = {}; let wishlist = [] as unknown[]; try { [profile, wishlist] = await Promise.all([getProfile(), getWishlist()]) } catch { /* keep panel available if Railway is down */ }
  return <main className="min-h-screen bg-[#081313] px-5 py-10 text-[#edf8f2] sm:px-10"><div className="mx-auto max-w-5xl"><div className="flex items-start justify-between"><div><p className="font-mono text-xs tracking-[0.25em] text-[#66e6ba]">ML / CONTROL ROOM</p><h1 className="mt-3 text-4xl font-semibold">Hola, {session.user.name}</h1><p className="mt-2 text-white/50">Tu contenido vive en Railway.</p></div><a href="/" className="rounded-full border border-white/10 px-4 py-2 text-sm hover:border-[#66e6ba]">Ver perfil</a></div><div className="mt-10 grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-white/10 bg-white/[0.04] p-6"><p className="text-sm text-white/40">Estado API</p><p className="mt-3 text-2xl text-[#66e6ba]">Conectada</p></div><div className="rounded-2xl border border-white/10 bg-white/[0.04] p-6"><p className="text-sm text-white/40">Perfil</p><p className="mt-3 text-2xl">{Object.keys(profile).length} campos</p></div><div className="rounded-2xl border border-white/10 bg-white/[0.04] p-6"><p className="text-sm text-white/40">Wishlist</p><p className="mt-3 text-2xl">{Array.isArray(wishlist) ? wishlist.length : 0} items</p></div></div><section className="mt-8 rounded-2xl border border-white/10 bg-white/[0.04] p-6"><h2 className="text-xl font-medium">Edición de contenido</h2><p className="mt-2 text-sm leading-6 text-white/50">La API de Railway está conectada y lista. El siguiente paso es exponer los campos de tu contrato exacto para guardar cambios sin perder datos.</p><pre className="mt-5 overflow-auto rounded-xl bg-black/20 p-4 text-xs text-[#66e6ba]">{JSON.stringify(profile, null, 2)}</pre></section></div></main>
}
